### ISSUE TITLE
Repos are not accessible/missing

### ISSUE THREAD

**Issue by TeeMorris** [GSA/code-gov#10]
@froi @saracope @jlow81  

When you search for Repos under "All" the projects are visible. When you try to do this by Agency, the Repos are missing. See attached screenshot.

<img width="1284" alt="screen shot 2018-07-11 at 8 58 53 am" src="https://user-images.githubusercontent.com/38725294/42573105-2e4ee2c0-84e9-11e8-8d59-0833ab29e219.png">

**Comment by froi** [comment]
I'm on it.

**Comment by froi** [comment]
The issue has been resolved. There was an issue with a timeout while writing to Elasticsearch.
