### ISSUE TITLE
Bad redirect

### ISSUE THREAD

**Issue by danielimmke** [GSA/code-gov#136]
This link: https://code.gov/about/compliance/inventory-code

Is redirecting to just code.gov. I was only able to get to it by navigating through the website. I am planning on including it in some READMEs so need it to be direct linkable.

**Comment by jcastle** [comment]
Hi @danielimmke, looks like when I past https://code.gov/federal-agencies/compliance/inventory-code into my browser, it goes to the page. You should be good to use it in README files.

**Comment by danielimmke** [comment]
Hmm yeah it seems to be resolved now. I'm still getting some odd behavior where when I hit enter in the url bar the link flashes to include a ?p= before changing back to the original link structure. Maybe this is an intermittent issue

**Comment by jcastle** [comment]
@danielimmke 

Yes, seems to be on refresh, it does another call for the URL. That shouldn't affect direct linking. Thanks for submitting the issue. Cheers!
