### ISSUE TITLE
Please add FEC to code.gov after 8/28

### ISSUE THREAD

**Issue by lbeaufort** [GSA/code-gov#16]
Hi there! 👋 

@RicardoAReyes asked me to put in an issue to add the FEC (Federal Election Commission) to code.gov.

We are [in the process](https://github.com/fecgov/fec-cms/pull/2260) of adding our code.json file to fec.gov - the change is scheduled to go live on Tuesday 8/28.

When you’re ready (anytime after 8/28) can you please add the FEC (Federal Election Commission) to the list of agencies (here’s a link to our agency seal: https://www.fec.gov/static/img/seal.svg) and scrape our https://www.fec.gov/code.json file?

Please let me know if you have any questions, or if I can help in any way. Thank you to @RicardoAReyes for being exceptionally helpful with this process!

**Comment by RicardoAReyes** [comment]
@lbeaufort thank you for doing all the leg work and getting FEC involved with the OMB M-16-21 FSCP! We look forward to indexing FECs open source code on Code.gov.

**Comment by RicardoAReyes** [comment]
@lbeaufort and @froi the FEC code is now published 

https://www.fec.gov/code.json

**Comment by RicardoAReyes** [comment]
Hi @lbeaufort, @froi complete the FEC integration on Code.gov and deployed the API update last night.

https://code.gov/#!/browse-projects?agencies=FEC

**Comment by lbeaufort** [comment]
@RicardoAReyes @froi that is great, thank you!!

Can you please update the agency name to "Federal Election Commission"? (Not "Federal Election**s** Commission) 

Thanks again!

**Comment by lbeaufort** [comment]
@RicardoAReyes @froi I thought I'd try to be useful and put in a PR: https://github.com/GSA/code-gov-api/pull/258

Thanks for all your hard work!

**Comment by froi** [comment]
Thanks for the PR @lbeaufort!

**Comment by froi** [comment]
I'm closing this issue as resolved by the PR submitted by @lbeaufort
