### ISSUE TITLE
Ability to denote projects as exempt on code.json inventory.

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov#22]
All Code-JSON Generator Tools should be able to inventory their exempt projects as required by the OMB-16-21 FSCP.

**Comment by froi** [comment]
@RicardoAReyes can this issue be closed?

**Comment by RicardoAReyes** [comment]
yes, we have listed the business and functional requirements on the respective agency scraper tool repos. The LLNL Scraper tool already addresses this requirement.
