### ISSUE TITLE
City/Municipal partnerships

### ISSUE THREAD

**Issue by mateoclarke** [GSA/code-gov#28]
Hi 👋 ,

The City of Austin would love to pilot how we might work with code.gov. 
Currently we use, https://helpwanted.team/austindotgov to solicit volunteer contributions from our local civic tech volunteer community.

We'd love to start a discussion on how we could share our help wanted issues building on top of what you've already done. Either by forking this project, or allowing users to code.gov see us as a related agency.

Best,
Mateo Clarke
mateo.clarke@austintexas.gov
Software Engineer, City of Austin

cc/ @ifsimicoded, @benweatherman, @luqmaan, @briaguya

**Comment by jcastle** [comment]
We approached this subject with our Legal team and found our funding approach only allows us to feature and support federal source code. We are happy to offer advice to state and local organizations and they are may fork our code.gov repo(s) to create own site(s).
