### ISSUE TITLE
Code.gov Administration Tool for Agency Inventory Upload and Maintenance

### ISSUE THREAD

**Issue by jcastle** [GSA/code-gov#29]
**Issue Description:**
This task supports the Code.gov team. We have an admin tool prototype and want to bring it to production for agency use.  There is both a front-end web interface and a database.

_Specific tasks:_

1. Get the current prototype admin tool working.  Front-end repo here - https://github.com/GSA/code-gov-admintool; Back-end repo here - https://github.com/GSA/code-gov-admin-backend.
2. Work with the Code.gov team and me (Joe Castle) to determine path forward for production.  This includes integration with Code.gov, including the environment with security, CI, code scanning, databases, etc.

**Contact Info:**
Name: Joseph Castle
Email: joseph.castle@gsa.gov

**Comment by seakintruth** [comment]
Does this tool also perform URL validation?  

Similar to the Code.json Validator it would be helpful to report broken URL links in the Code.json file.

I put together a google sheets prototype of sorts here:
https://docs.google.com/spreadsheets/d/13tzylBYFAISHDaN9QOgL-qIj4we0V7X_Jz_pyzKYrxU/edit?usp=sharing

It publishes a daily report to here:
https://docs.google.com/spreadsheets/d/e/2PACX-1vQm1kqCv30grzurClLrYTGb3P-itY07Cbl70Hu-7UBEIAKAiz3s8v1y-VFAp4vLqaH3qQ2FVilRSFHb/pubhtml

This tool attempts to daily import each agency's code.json file as described by the code.gov site and verify pertinent URLs for each agency's code.json file. These verifications are displayed on the UrlStatus worksheet. This report displays the HTTPS response codes when >=300 from a call to Google App Script UrlFetch() for each URL.

It works as is, but only validates files that are found from the existing agencies code.json files.

**Comment by jcastle** [comment]
Test issue for hiding.

**Comment by jcastle** [comment]
This was originally listed as a Help Wanted task to create something similar to inventory.data.gov. With current resource constraints, I am going to close for now.
