### ISSUE TITLE
Should we add securityCertifications to the Schema? 

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov#30]
Coming out of [this great idea](https://github.com/GSA/code-gov-web/issues/196#issuecomment-268908981) from @jqnatividad

**Comment by froi** [comment]
I love this idea. It's the kind of feedback that I think we should go for. @jcastle, @AminPIC, @saracope thoughts?

I would love to see this incorporated into a discovery sprint geared to procurement officers and federal developers needs.

**Comment by jcastle** [comment]
@DanielJDufour and @froi, we are looking to update the schema. Can you elaborate on what you mean by this? What would agencies list for securityCertifications?

**Comment by DanielJDufour** [comment]
Sure.  I think the intent was to capture the relevant security information that someone approving the use of a library found on code.gov might ask for.  A few values come to mind: `fedramp`, `authority-to-operate`, `disa-stig-compliant`, `certificate-to-field`.  Those could be boolean values for the first pass.  If we wanted to be more thorough, we could find a way to capture the following information:
1) If the library represents a deployed, does it have an Authority to Operate?  If yes, who authorized it and what is their contact information, so potential re-users know who to reach out to.
2) FedRAMP Certification.  Who is the point of contact for this information?
3) Does is comply with DISA's STIGs (https://public.cyber.mil/stigs/)?
4) Does it have a certificate to field? Who is the point of contact for this? (CtF are for libraries whereas ATOs are for systems)

Naturally in the military space (DISA Stigs, Certificate to Fields, etc.), we have to be more careful.  The actual paperwork authorizing something is usually FOUO or higher, but I'm not sure whether something has an ATO is FOUO?

Happy to brainstorm more :-)

**Comment by DanielJDufour** [comment]
@jqnatividad, are there any more security questions/tags that you think should be captured?

**Comment by leebrian** [comment]
For my agency, we certify systems with ATO and the source is only part of that. To add this to the schema we have to be careful about what the attribute means as the same source code could be used in a system that receives an ATO as well as one that fails to. 

I don’t know how useful to me in working with my security folks to know that source code was used in an ATO system or used in a FedRAMP system. 

If there are security certifications for the source code itself, that would be helpful, knowing that a particular release passed a defined certification for source quality.

**Comment by jcastle** [comment]
Thanks @leebrian, you are invited to our internal meeting tomorrow regarding the schema. Like you said, not sure how helpful it is to add for ATO or FedRamp.

**Comment by leebrian** [comment]
I’m planning on attending and looking forward to it. I think an improved schema will really help produce more useful metadata on projects and improve quality and reuse. Thanks for coordinating the call.

**Comment by jcastle** [comment]
Will take into consideration for future metadata schemas. Thanks for the initial issue.
