### ISSUE TITLE
Github blocked by Cyber

### ISSUE THREAD

**Issue by Radshat** [GSA/code-gov#31]
Github has been blocked by our federal oversight so we are unable to contribute. I am confused how this is supposed to work if the federal oversight is not all on board. Has this been discussed before?

**Comment by saracope** [comment]
Tagging @jcastle and @AminPIC for visibility.

**Comment by jcastle** [comment]
@Radshat, I am afraid I don't understand your request. What agency are you associated with and/or which agencies are blocking GitHub (I assume you mean access to GitHub.com). There are some federal agencies that have a no GitHub use policy but this is changing over time. We may be able to help if we have more information. Thanks!

**Comment by Radshat** [comment]
Y12 and Pantex is under the DOE & NNSA. NNSA Production Office has explicitly blocked Github.com.

If there is a way to get across the code.gov initiative to our oversight maybe that would help getting github unblocked.

**Comment by jcastle** [comment]
@Radshat, you should connect with @IanLee1521 regarding DOE code. He is at LLNL and they exclusively publish to GitHub.com. He is also in contact with DOE Code - https://www.osti.gov/doecode/ - and should be able to point you to someone there. Maybe consider doing this through internal channels too.

From a Code.gov perspective, we can't mandate agencies use a public platform only that they comply with M-16-21, Federal Source Code Policy.

**Comment by Radshat** [comment]
Thanks, that gives me a starting point!

**Comment by IanLee1521** [comment]
@Radshat -- Feel free to reach out to me via email. I would be happy to set up a call and discuss. `ian` + `@llnl.gov`

**Comment by saracope** [comment]
Closing this as it looks like the convo has moved to another platform.
