### ISSUE TITLE
Update helpwanted.md

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov#37]
It should include info on the content tag which we're using on the front end.
https://github.com/GSA/code-gov/blob/master/HelpWanted.md

<img width="334" alt="Screen Shot 2019-05-07 at 5 38 14 PM" src="https://user-images.githubusercontent.com/2197515/57335306-2bc05e00-70f0-11e9-99ef-049bfd77962b.png">

**Comment by stim371** [comment]
Was this issue addressed in this commit? https://github.com/GSA/code-gov/commit/fe7743c5f1cddb228c4d20fb258ef6c4bdc1c97f

**Comment by saracope** [comment]
Yep, closing out. Thanks!
