### ISSUE TITLE
Issue with multiple agencies adding the same github repo to their inventories

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov#41]
Example: the WNTR project is being cataloged by DOE and EPA. We have 2 entries for it:
https://code.gov/search?page=1&query=wntr&size=10&sort=best_match

They both point to the same repository on GitHub.

@RicardoAReyes Can this be removed from one of the agency code inventories so it's only being cataloged once?

**Comment by jcastle** [comment]
This is not uncommon. Agencies are notified and asked to correct. Not all comply and really not a big issue. Worst case is repos will be listed by multiple agencies taking the total repo count up a little.
