### ISSUE TITLE
Feature Request: Shrink Search Results Payload with Protobufs

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov#50]
I'm not sure where to place this issue because it would touch the backend, api-client, and code-gov-front-end.  Have you considered creating a Protocol Buffer format for the code.gov API results, specifically the /repos endpoint.  It would shrink the size of the results JSON by a lot and allow us to ship a lot more search results (and get rid of the limit of 100 results put in for performance reasons).  Let me know if this is of interest to you and I can start working on it :-)

**Comment by jcastle** [comment]
@seanstar12, what do you think of this? It's okay if we can't resource this right now. Maybe provide your thoughts and close if needed.

**Comment by jcastle** [comment]
Going to close for now since this isn't our focus with limited resources.
