### ISSUE TITLE
Add a docs folder

### ISSUE THREAD

**Issue by saracope** [GSA/code-gov#54]
We have a handful of files for documentation of the platform overall. We should clean up the organization of these a bit.

Tasks:
- Create a new folder named `docs`
- Move all the files that are code.gov specific to new docs folder
- Standardize the naming so these are all lower case
- Update the `Files you'll find in this repo` listing in [README.md](https://github.com/GSA/code-gov/blob/master/README.md) so the file references point to the new location
- Double-check that all of the code.gov specific docs files are in the Files list in [README.md](https://github.com/GSA/code-gov/blob/master/README.md)

**Comment by Armenm** [comment]
Hi @saracope and @mvedataydin ,

I found a couple of broken links after this cleanup and opened 2 pull requests.

https://github.com/GSA/code-gov/pull/57
https://github.com/GSA/code-gov/pull/58
