### ISSUE TITLE
April 16th, 2020 Event

### ISSUE THREAD

**Issue by mgifford** [GSA/code-gov#63]
- [x ] Code.gov

Ok, I'm a Drupal Maintainer & have contributed to 18F documentation, but basically wanted to write about the April 16th, 2020 Code.gov event.  I was told in your newsletter I could submit questions here. 

I have an accessibility newsletter largely aimed to Canadian Government agencies.  Will your April event be open to the Canadian government and will there be much focus on accessibility (Section 508)?

**Comment by JosephAmalfitanoSSA** [comment]
I'll defer to @jcastle for content of the April event.

As far as accessibility goes, it seems like a perfect time for some shameless promotion one of our open source projects 😄  

### ANDI - Accessibility Name and Description Inspector. 

#### Here's the repo:
<https://github.com/SSAgov/ANDI/>

#### How to install
<https://www.ssa.gov/accessibility/andi/help/install.html>

#### How to use
<https://www.ssa.gov/accessibility/andi/help/howtouse.html>

**Comment by jcastle** [comment]
@mgifford, the event is open to U.S. federal government. For feds by feds. Maybe we can get you next time as we see how this event goes and open it up to others. Thank you for your interest!

**Comment by mgifford** [comment]
No problem.  @jcastle Mostly I wanted to know if other public servants should know about it, particularly the feds here in Canada.  Lots of opportunities to collaborate, plus a bunch of USA feds have come up to work with governments in Canada.
