### ISSUE TITLE
CFPB -new-clouseau- repo not found 

### ISSUE THREAD

**Issue by froi** [GSA/code-gov#8]
# What's the issue

The repository [cfpb/-new-clouseau-](https://github.com/cfpb/-new-clouseau-) is inventoried in Code.gov and identified as open source but cannot be found on Github. Either the repo trully does not exist, has been marked as private, is missed labeled as `openSource`, or the name is wrong.

Here are some screenshots:

__Repo in the `All` list:__
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1918027/41999804-c2c0aa78-7a2c-11e8-9631-9c60ce5a840a.png">

__Project's details page:__
<img width="661" alt="image" src="https://user-images.githubusercontent.com/1918027/41999821-cdf6b176-7a2c-11e8-953f-39e0972f7759.png">

__Github 404 page:__
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/1918027/41999669-4c567afc-7a2c-11e8-84fb-3ec8d0b3e78b.png">

# Possible Solutions

1. Ask CFPB to fix the entry in their `code.json` if the project is meant to be `governmentWideReuse` or `exempt`
2. Ask CFPB to set the project as public on Github
3. Ask CFPB to eliminate the project form their `code.json` if the project no longer exists.

# Who Should Look Into This

* @RicardoAReyes 
* @jcastle

**Comment by DanielJDufour** [comment]
@froi, good catch.  We could also consider the pros and cons of writing a script that checks for broken links. We could then hide the repo link button or hide the repository as a whole if there's a bug with it.

**Comment by froi** [comment]
Yeah, that rake test is a TODO I have in the backend when harvesting. [code-gov-api Issue #207](https://github.com/GSA/code-gov-api/issues/207)

**Comment by RicardoAReyes** [comment]
Following up with CFPB open source lead and software engineer (@contolini) developing the CFBP Code-JSON Generator/Scraper tool.

**Comment by RicardoAReyes** [comment]
Hi @contolini,

From our last conversation, you are still working on your code.json generator tool to complete the software inventory update on the code.json file -correct?

**Comment by Scotchester** [comment]
This issue was opened the day after we most recently updated our `code.json` file.

-new-clouseau- no longer appears in the list on code.gov, so it looks like shortly after the issue was opened, code.gov indexed our latest `code.json` file, which (as @hillaryj mentioned) no longer includes that repo. I think this issue can be closed.

**Comment by froi** [comment]
@Scotchester Confirmed. `-new-clouseau-` repo is no longer in the inventory.

Executing the following returns 0 results:

```bash
curl "https://api.code.gov/repos/?name=-new-clouseau-" \
     -H 'Content-Type: application/json' \
     -H 'X-Api-Key: <your-api-key>'
```

```json
{
  "total": 0,
  "repos": []
}
```
