### ISSUE TITLE
ARL DCCSO project not reachable.

### ISSUE THREAD

**Issue by froi** [GSA/code-gov#9]
The Army Research Lab has published the __U.S. Army Research Laboratory (ARL) Discrete Chemical Compound Space Optimization (DCCSO)__ project and has marked it as open source, but it is not reachable using  [https://github.com/USArmyResearchLab/DCCSO](https://github.com/USArmyResearchLab/DCCSO).

__Expected Behaviour__
The DCCSO project should be reachable using [https://github.com/USArmyResearchLab/DCCSO](https://github.com/USArmyResearchLab/DCCSO)

__Current Behaviour__

The DCCSO project is unreachable using [https://github.com/USArmyResearchLab/DCCSO](https://github.com/USArmyResearchLab/DCCSO)

<img width="869" alt="image" src="https://user-images.githubusercontent.com/1918027/42546076-920e125a-8489-11e8-93c5-37e80a86f6e8.png">

__Possible Solution__
Very if the project was marked `openSource` by mistake or if the access to the project needs to be fixed/changed.

**Comment by froi** [comment]
CC. @RicardoAReyes @jcastle

**Comment by saracope** [comment]
@RicardoAReyes Can you investigate this repo?

**Comment by AminPIC** [comment]
got the correct repo, but also requested them to update the code.json to reflect the actual link. 

here it is in case: https://github.com/USArmyResearchLab/ARL_Discrete_Chemical_Compound_Space_Optimization

**Comment by AminPIC** [comment]
The URL link has been updated so this issue can be closed.
